/*	Generated by configure. Don't edit!!!!	*/

#undef CONFIGURE_SOUNDCARD
#undef KERNEL_SOUNDCARD
#define SOUND_VERSION_STRING "2.4"
#define SOUND_CONFIG_DATE "2025年 08月 25日 星期一 18:00:47 CST"
#define SOUND_CONFIG_BY "dingjing"
#define SOUND_CONFIG_HOST "gentoo-pc"
#define SOUND_CONFIG_DOMAIN ""
